/**
 * Invoice PDF Service
 *
 * Generates professional, fileable PDFs for invoices.
 * Uses PDFKit for layout and typography.
 */

const PDFDocument = require('pdfkit');
const Invoice = require('../models/Invoice');
const Business = require('../models/Business');

/**
 * Format USD cents as currency string
 */
function formatCents(cents) {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format((cents || 0) / 100);
}

/**
 * Generate invoice PDF as buffer
 *
 * @param {string} invoiceId - Invoice ID
 * @param {string} baseUrl - Frontend base URL for payment link (e.g. https://app.example.com)
 * @returns {Promise<Buffer>}
 */
async function generateInvoicePdf(invoiceId, baseUrl = 'http://localhost:3000') {
  const invoice = await Invoice.findById(invoiceId);
  if (!invoice) {
    throw new Error('Invoice not found');
  }

  const business = await Business.findById(invoice.businessId);
  const businessName = business?.name || 'Business';

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const paymentUrl = `${baseUrl.replace(/\/$/, '')}/pay/${invoiceId}`;

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text(businessName, 50, 50);
    doc.fontSize(10).font('Helvetica').fillColor('#666666').text('INVOICE', 50, 78);

    // Invoice number and dates (right-aligned)
    doc.fontSize(10).font('Helvetica').fillColor('#000000');
    doc.text(`Invoice #${invoice.invoiceNumber}`, 400, 50, { width: 150, align: 'right' });
    doc.text(`Issue date: ${new Date(invoice.issueDate || invoice.createdAt).toLocaleDateString('en-US')}`, 400, 65, { width: 150, align: 'right' });
    doc.text(`Due date: ${new Date(invoice.dueDate).toLocaleDateString('en-US')}`, 400, 80, { width: 150, align: 'right' });
    doc.text(`Status: ${invoice.status}`, 400, 95, { width: 150, align: 'right' });

    // Bill To
    doc.fontSize(11).font('Helvetica-Bold').text('Bill To', 50, 130);
    doc.fontSize(10).font('Helvetica');
    doc.text(invoice.clientName, 50, 148);
    if (invoice.clientEmail) {
      doc.text(invoice.clientEmail, 50, 163);
    }
    if (invoice.clientAddress) {
      doc.text(invoice.clientAddress, 50, 178);
    }

    // Line items table
    const tableTop = 220;
    doc.fontSize(10).font('Helvetica-Bold');
    doc.text('Description', 50, tableTop);
    doc.text('Qty', 320, tableTop);
    doc.text('Unit Price', 380, tableTop);
    doc.text('Amount', 460, tableTop);

    doc.moveTo(50, tableTop + 18).lineTo(550, tableTop + 18).stroke();
    doc.font('Helvetica');

    let y = tableTop + 28;
    for (const item of invoice.items || []) {
      if (y > doc.page.height - 100) {
        doc.addPage();
        y = 50; // Reset Y to top of new page
      }
      doc.text(String(item.description).slice(0, 50), 50, y, { width: 260 });
      doc.text(String(item.quantity), 320, y);
      doc.text(formatCents(item.unitPrice), 380, y);
      doc.text(formatCents(item.amount), 460, y);
      y += 22;
    }

    y += 12;
    doc.moveTo(350, y).lineTo(550, y).stroke();
    y += 20;

    doc.font('Helvetica');
    doc.text('Subtotal', 350, y);
    doc.text(formatCents(invoice.subtotal), 460, y);
    y += 22;

    if (invoice.tax && invoice.tax > 0) {
      doc.text('Tax', 350, y);
      doc.text(formatCents(invoice.tax), 460, y);
      y += 22;
    }

    doc.font('Helvetica-Bold');
    doc.text('Total', 350, y);
    doc.text(formatCents(invoice.total), 460, y);
    y += 35;

    // Notes
    if (invoice.notes) {
      doc.font('Helvetica').fontSize(9).fillColor('#555555');
      doc.text('Notes', 50, y);
      doc.text(invoice.notes, 50, y + 14, { width: 500 });
      y += 50;
    }

    // Payment instructions (for SENT/PENDING)
    if (['SENT', 'PENDING'].includes(invoice.status)) {
      doc.font('Helvetica').fontSize(10).fillColor('#000000');
      doc.text('Pay this invoice online:', 50, y + 20);
      doc.fillColor('#2563eb').text(paymentUrl, 50, y + 38, { link: paymentUrl });
      doc.fillColor('#000000').fontSize(9).text('Open the link above to pay with Solana or Ethereum.', 50, y + 58);
    }

    // Footer
    const bottomMargin = doc.page.margins.bottom; // 1. Save current margin
    doc.page.margins.bottom = 0;                  // 2. Remove bottom margin restriction

    doc.fontSize(8).fillColor('#999999');
    doc.text(
      `Generated by Nova • Invoice ${invoice.invoiceNumber} • ${new Date().toISOString().slice(0, 10)}`,
      50,
      doc.page.height - 50,
      { width: 500, align: 'center' }
    );

    doc.page.margins.bottom = bottomMargin; // 3. Restore original margin

    doc.end();
  });
}

module.exports = {
  generateInvoicePdf,
  formatCents,
};
